### ISSUE TITLE
hw01 TA feedback

### ISSUE THREAD

**Issue by dy-lin** [yuliaUU/STAT545-participation#2]
hi @yuliaUU 

I left you a message on Canvas regarding my hw01 evaluation.

I just took a closer look and realize your comment about functions is for exercise 1.
I think you may have looked at the wrong README for my evaluation.

Take a look at the README for the hw __REPO__ in my hw01 tagged release.
https://github.com/STAT545-UBC-hw-2019-20/stat545-hw-dy-lin/tree/hw1.1

On the assignment1 page it says:

> Your task here is to edit the main README.md file in your repository

and on the assignments main page:

> Each assignment should be self-contained in a folder within your STAT 545A homework repository, found in the hw Org.
  Special case for Assignment 01, which also evaluates your repo’s README.md file.

The README I used to fulfill Assignment 1 was this one (it even says in the README):
https://github.com/STAT545-UBC-hw-2019-20/stat545-hw-dy-lin/blob/hw1.1/README.md

I fulfilled the requirements in the README for the repo, not the smaller one I made later for the hw01 folder.

Can I get a re-evaluation?

**Comment by yuliaUU** [comment]
Hi
Remarked it! I clearly was confused as there was no link to the README file in your Assignment 1 submission. I remarked it !
